.TH SETPROP 1 "July 1, 2013"
.SH NAME
setprop \- set property via the android property service
.SH SYNOPSIS
.B setprop
.RI "property value"
.SH DESCRIPTION
.PP
\fBsetprop\fP is an android utility to set up a property via the android property service.
.SH OPTIONS
.TP
.B property
Name of the property to be set
.TP
.B value
Value of the property (string, numbers, etc)
.SH AUTHOR
setprop is originally available in the Android AOSP project.
.PP
This manual page was written by Ricardo Salveti de Araujo <ricardo.salveti@canonical.com>,
for the Debian project (and may be used by others).
